- hosts: localhost
  tasks:
    - name: Retrieve public ips of VMs in resource group
      azure_rm_publicipaddress_facts:
        resource_group: Testing
      register: ip_addresses

    - name: Add hosts to playbook hosts record
      add_host:
        name: "{{ item.properties.ipAddress }}"
        group: azure_vms
      with_items: "{{ ip_addresses.ansible_facts.azure_publicipaddresses }}"

- hosts: azure_vms
  remote_user: azure_user
  tasks:
    - name: Add/Remove new user public key
      authorized_key:
        user: azure_user
        key: "{{ lookup('file', './newuserkey.pub') }}"
        #state: absent
      register: shell_out

#Assertion to check can/can't login using ssh -i newuserkey?