# Initial version of this script came from the Ansible Azure documentation. https://docs.ansible.com/ansible/guide_azure.html
# Commands run against Azure are run from localhost
- hosts: localhost
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: Testing
        location: westeurope

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: Testing
        name: testvn001
        address_prefixes: "10.10.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: Testing
        name: subnet001
        address_prefix: "10.10.0.0/24"
        virtual_network: testvn001

    - name: Create security group that allows SSH
      azure_rm_securitygroup:
        resource_group: Testing
        name: secgroup001
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound
    
    - name: Run tasks needed for each VM
      include: "create-per-vm-resources.yml vm_number={{item}}"
      with_sequence: count=2

# If Ansible hasn't failed this playbook, VMs probably exist.
# Steps below are proving the VMs exist for ourselves

    - name: Print hosts in azure_vms groups
      debug:
        var: groups['azure_vms']
        # Only print if playbook is run with a -v verbosity or higher
        verbosity: 1

# For the hosts we've put in the group azure_vms, run some shell commands to prove existence, connectivity.
- hosts: azure_vms
  remote_user: azure_user
  tasks:
    - name: Run whoami, hostname and uptime on new VMs
      shell: whoami; hostname; uptime
      register: shell_out

    - name: Print shell output from previous task
      debug:
        msg: shell_out
        verbosity: 1