- hosts: localhost
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: Testing
        location: westeurope

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: Testing
        name: testvn001
        address_prefixes: "10.10.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: Testing
        name: subnet001
        address_prefix: "10.10.0.0/24"
        virtual_network: testvn001

    - name: Create public ips
      azure_rm_publicipaddress:
        resource_group: Testing
        allocation_method: Static
        name: "publicip00{{ item }}"
      register: ip_addresses
      with_sequence: count=2

    - name: Create security group that allows SSH
      azure_rm_securitygroup:
        resource_group: Testing
        name: secgroup001
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound

    - name: Create NICs
      azure_rm_networkinterface:
        resource_group: Testing
        name: "testnic00{{ item }}"
        virtual_network: testvn001
        subnet: subnet001
        public_ip_name: "publicip00{{ item }}"
        security_group: secgroup001
      with_sequence: count=2

    - name: Create virtual machines
      azure_rm_virtualmachine:
        resource_group: Testing
        name: "testvm00{{ item }}"
        vm_size: Standard_D1
        ssh_password_enabled: false
        ssh_public_keys: 
          - path: /home/azure_user/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        admin_username: azure_user
        network_interfaces: "testnic00{{ item }}"
        image:
          offer: UbuntuServer
          sku: 16.04-LTS
          version: latest
          publisher: Canonical
      register: vm_facts
      with_sequence: count=2

    - name: Add hosts to playbook hosts record
      add_host:
        name: "{{ item.state.ip_address }}"
        group: azure_vms
      with_items: "{{ ip_addresses.results }}"

    - name: Print hosts in azure_vms groups
      debug:
        var: groups['azure_vms']

- hosts: azure_vms
  remote_user: azure_user
  tasks:
    - name: Run whoami, hostname and uptime on new VMs
      shell: whoami; hostname; uptime
      register: shell_out

    - name: Print shell output from previous task
      debug:
        msg: shell_out