# Initial version of this script came from the Ansible Azure documentation. https://docs.ansible.com/ansible/guide_azure.html
# Commands run against Azure are run from localhost
- hosts: localhost
  tasks:
    - name: Run tasks needed for each resource group
      include: create-per-resource-group-resources.yml resource_group=Testing

    - name: Run tasks needed for each VM
      include: create-per-vm-resources.yml
      vars: 
        vm_number: "{{item}}"
        resource_group: Testing
      with_sequence: count=2

# If Ansible hasn't failed this playbook, VMs probably exist.
# Steps below are proving the VMs exist for ourselves

    - name: Print hosts in azure_vms groups
      debug:
        var: groups['azure_vms']
        # Only print if playbook is run with a -v verbosity or higher
        verbosity: 1

# For the hosts we've put in the group azure_vms, run some shell commands to prove existence, connectivity.
- hosts: azure_vms
  remote_user: azure_user
  tasks:
    - name: Run whoami, hostname and uptime on new VMs
      shell: whoami; hostname; uptime
      register: shell_out

    - name: Print shell output from previous task
      debug:
        msg: shell_out
        verbosity: 1